export const teacherStatsData = [
    {
        id: 1,
        title: 'My Students',
        count: 12,
        iconType: 'users',
        bgColor: 'bg-blue-50',
    },
    {
        id: 2,
        title: 'Schedule Class',
        count: 24,
        iconType: 'calendar',
        bgColor: 'bg-orange-50',
    },
    {
        id: 3,
        title: 'Learning Material',
        count: 5,
        iconType: 'book',
        bgColor: 'bg-purple-50',
    },
    {
        id: 4,
        title: 'Progress',
        count: '2%',
        iconType: 'chart',
        bgColor: 'bg-red-50',
    },
];

export const upcomingClassesData = [
    {
        id: 1,
        className: 'Advance Chemistry',
        time: '14:00 - 16:30 PM',
        room: 'Room 305, Arts Building',
        tags: ['Skill Path', 'Data'],
    },
    {
        id: 2,
        className: 'Advance Chemistry',
        time: '14:00 - 16:30 PM',
        room: 'Room 305, Arts Building',
        tags: ['Skill Path', 'Data'],
    },
    {
        id: 3,
        className: 'Advance Chemistry',
        time: '14:00 - 16:30 PM',
        room: 'Room 305, Arts Building',
        tags: ['Skill Path', 'Data'],
    },
];

export const pendingReviewsData = [
    {
        id: 1,
        courseName: 'C++ Programming',
        tag: 'Data',
        pendingCount: 12,
        avatars: [
            'https://i.pravatar.cc/150?img=1',
            'https://i.pravatar.cc/150?img=2',
            'https://i.pravatar.cc/150?img=3',
        ],
    },
    {
        id: 2,
        courseName: 'C++ Programming',
        tag: 'Data',
        pendingCount: 12,
        avatars: [
            'https://i.pravatar.cc/150?img=4',
            'https://i.pravatar.cc/150?img=5',
            'https://i.pravatar.cc/150?img=6',
        ],
    },
    {
        id: 3,
        courseName: 'C++ Programming',
        tag: 'Data',
        pendingCount: 12,
        avatars: [
            'https://i.pravatar.cc/150?img=7',
            'https://i.pravatar.cc/150?img=8',
            'https://i.pravatar.cc/150?img=9',
        ],
    },
];

export const teacherRecentActivityData = [
    {
        id: 1,
        title: '23 Students under your guidance',
        subTitle: 'View only access',
        iconType: 'graduation',
        bgColor: 'bg-purple-50',
    },
    {
        id: 2,
        title: '23 Students under your guidance',
        subTitle: 'View only access',
        iconType: 'graduation',
        bgColor: 'bg-purple-50',
    },
    {
        id: 3,
        title: '23 Students under your guidance',
        subTitle: 'View only access',
        iconType: 'graduation',
        bgColor: 'bg-purple-50',
    },
];

export const classSchedulesData = [
    {
        key: '1',
        title: 'Git Foundation & Github',
        description: 'The session introduces version control and collaboration using Git and GitHub.',
        date: '11/12/2025',
        time: '08:12 am',
        location: '12 central street road',
        targets: ['Skill Path', 'Data'],
        status: 'Active',
    },
    {
        key: '2',
        title: 'Git Foundation & Github',
        description: 'The session introduces version control and collaboration using Git and GitHub.',
        date: '11/12/2025',
        time: '08:12 am',
        location: '12 central street road',
        targets: ['Skill Path', 'Data'],
        status: 'Active',
    },
    {
        key: '3',
        title: 'Git Foundation & Github',
        description: 'The session introduces version control and collaboration using Git and GitHub.',
        date: '11/12/2025',
        time: '08:12 am',
        location: '12 central street road',
        targets: ['Skill Path', 'Data'],
        status: 'Active',
    },
    {
        key: '4',
        title: 'Git Foundation & Github',
        description: 'The session introduces version control and collaboration using Git and GitHub.',
        date: '11/12/2025',
        time: '08:12 am',
        location: '12 central street road',
        targets: ['Skill Path', 'Data'],
        status: 'Active',
    },
    {
        key: '5',
        title: 'Git Foundation & Github',
        description: 'The session introduces version control and collaboration using Git and GitHub.',
        date: '11/12/2025',
        time: '08:12 am',
        location: '12 central street road',
        targets: ['Skill Path', 'Data'],
        status: 'Active',
    },
    {
        key: '6',
        title: 'Git Foundation & Github',
        description: 'The session introduces version control and collaboration using Git and GitHub.',
        date: '11/12/2025',
        time: '08:12 am',
        location: '12 central street road',
        targets: ['Skill Path', 'Data'],
        status: 'Active',
    },
    {
        key: '7',
        title: 'Git Foundation & Github',
        description: 'The session introduces version control and collaboration using Git and GitHub.',
        date: '11/12/2025',
        time: '08:12 am',
        location: '12 central street road',
        targets: ['Skill Path', 'Data'],
        status: 'Active',
    },
    {
        key: '8',
        title: 'Git Foundation & Github',
        description: 'The session introduces version control and collaboration using Git and GitHub.',
        date: '11/12/2025',
        time: '08:12 am',
        location: '12 central street road',
        targets: ['Skill Path', 'Data'],
        status: 'Active',
    },
];

export const resourcesData = [
    {
        key: '1',
        title: 'Java_Script.pdf',
        description: 'This is for beginners',
        type: 'PDF',
        targets: ['Skill Path', 'Data'],
        uploadDate: '11/12/2025',
        status: 'Active',
        contentUrl: 'https://example.com/js.pdf',
        materialType: 'Learning Material',
    },
    {
        key: '2',
        title: 'Java_Script.pdf',
        description: 'This is for beginners',
        type: 'PDF',
        targets: ['Skill Path', 'Data'],
        uploadDate: '11/12/2025',
        status: 'Active',
        contentUrl: 'https://example.com/js.pdf',
        materialType: 'Learning Material',
    },
    {
        key: '3',
        title: 'Java_Script.pdf',
        description: 'This is for beginners',
        type: 'PDF',
        targets: ['Skill Path', 'Data'],
        uploadDate: '11/12/2025',
        status: 'Active',
        contentUrl: 'https://example.com/js.pdf',
        materialType: 'Learning Material',
    },
    {
        key: '4',
        title: 'Java_Script.pdf',
        description: 'This is for beginners',
        type: 'PDF',
        targets: ['Skill Path', 'Data'],
        uploadDate: '11/12/2025',
        status: 'Active',
        contentUrl: 'https://example.com/js.pdf',
        materialType: 'Learning Material',
    },
    {
        key: '5',
        title: 'Java_Script.pdf',
        description: 'This is for beginners',
        type: 'PDF',
        targets: ['Skill Path', 'Data'],
        uploadDate: '11/12/2025',
        status: 'Active',
        contentUrl: 'https://example.com/js.pdf',
        materialType: 'Learning Material',
    },
    {
        key: '6',
        title: 'Java_Script.pdf',
        description: 'This is for beginners',
        type: 'PDF',
        targets: ['Skill Path', 'Data'],
        uploadDate: '11/12/2025',
        status: 'Active',
        contentUrl: 'https://example.com/js.pdf',
        materialType: 'Learning Material',
    },
];
